-- Supabase PostgreSQL schema for BEI Screener historical persistence.
-- Audited against the active SQLite schema and analysis implementation.
-- Additive/idempotent only. This migration contains no DROP, TRUNCATE,
-- DELETE FROM, or ON DELETE CASCADE operations.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS upload_runs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_started_at timestamptz NOT NULL DEFAULT now(),
    source text NOT NULL DEFAULT 'app_upload',
    note text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS upload_ledger (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_run_id uuid REFERENCES upload_runs(id) ON DELETE RESTRICT,
    sha256 text NOT NULL UNIQUE,
    filename text NOT NULL,
    size_bytes bigint NOT NULL,
    rows_read integer NOT NULL DEFAULT 0,
    rows_saved integer NOT NULL DEFAULT 0,
    uploaded_at timestamptz NOT NULL DEFAULT now(),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS stock_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_run_id uuid REFERENCES upload_runs(id) ON DELETE RESTRICT,
    trade_date date NOT NULL,
    stock_code text NOT NULL,
    company_name text,
    open_price double precision,
    high_price double precision,
    low_price double precision,
    close_price double precision,
    volume double precision,
    value double precision,
    frequency double precision,
    foreign_sell double precision,
    foreign_buy double precision,
    net_foreign_buy double precision GENERATED ALWAYS AS (foreign_buy - foreign_sell) STORED,
    bid_price_1 double precision,
    bid_volume_1 double precision,
    ask_price_1 double precision,
    ask_volume_1 double precision,
    bid_price_2 double precision,
    bid_volume_2 double precision,
    ask_price_2 double precision,
    ask_volume_2 double precision,
    bid_price_3 double precision,
    bid_volume_3 double precision,
    ask_price_3 double precision,
    ask_volume_3 double precision,
    bid_price_4 double precision,
    bid_volume_4 double precision,
    ask_price_4 double precision,
    ask_volume_4 double precision,
    bid_price_5 double precision,
    bid_volume_5 double precision,
    ask_price_5 double precision,
    ask_volume_5 double precision,
    raw_data jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT stock_daily_stock_code_not_blank CHECK (btrim(stock_code) <> '')
);

CREATE TABLE IF NOT EXISTS orderbook_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_run_id uuid REFERENCES upload_runs(id) ON DELETE RESTRICT,
    stock_daily_id bigint REFERENCES stock_daily(id) ON DELETE RESTRICT,
    snapshot_date date NOT NULL,
    snapshot_time time NOT NULL DEFAULT '00:00:00',
    stock_code text NOT NULL,
    bid_price_1 double precision,
    bid_volume_1 double precision,
    ask_price_1 double precision,
    ask_volume_1 double precision,
    bid_price_2 double precision,
    bid_volume_2 double precision,
    ask_price_2 double precision,
    ask_volume_2 double precision,
    bid_price_3 double precision,
    bid_volume_3 double precision,
    ask_price_3 double precision,
    ask_volume_3 double precision,
    bid_price_4 double precision,
    bid_volume_4 double precision,
    ask_price_4 double precision,
    ask_volume_4 double precision,
    bid_price_5 double precision,
    bid_volume_5 double precision,
    ask_price_5 double precision,
    ask_volume_5 double precision,
    raw_data jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT orderbook_snapshot_stock_code_not_blank CHECK (btrim(stock_code) <> '')
);

CREATE TABLE IF NOT EXISTS technical_indicator_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_run_id uuid REFERENCES upload_runs(id) ON DELETE RESTRICT,
    stock_daily_id bigint REFERENCES stock_daily(id) ON DELETE RESTRICT,
    trade_date date NOT NULL,
    stock_code text NOT NULL,
    sma20 double precision,
    sma50 double precision,
    sma200 double precision,
    volume_ma20 double precision,
    volume_ratio double precision,
    rsi14 double precision,
    atr14 double precision,
    horizons_available integer,
    history_days integer,
    technical_status text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT technical_indicator_stock_code_not_blank CHECK (btrim(stock_code) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_upload_ledger_sha256
    ON upload_ledger (sha256);
CREATE INDEX IF NOT EXISTS idx_upload_ledger_filename
    ON upload_ledger (filename);
CREATE INDEX IF NOT EXISTS idx_upload_ledger_run
    ON upload_ledger (upload_run_id);
CREATE INDEX IF NOT EXISTS idx_upload_runs_started_at
    ON upload_runs (run_started_at);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stock_daily_run_date_code
    ON stock_daily (upload_run_id, trade_date, stock_code)
    WHERE upload_run_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_stock_daily_code_date
    ON stock_daily (stock_code, trade_date);
CREATE INDEX IF NOT EXISTS idx_stock_daily_trade_date
    ON stock_daily (trade_date);
CREATE INDEX IF NOT EXISTS idx_stock_daily_run
    ON stock_daily (upload_run_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_orderbook_snapshot_run_key
    ON orderbook_snapshot (upload_run_id, snapshot_date, snapshot_time, stock_code)
    WHERE upload_run_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orderbook_code_time
    ON orderbook_snapshot (stock_code, snapshot_date, snapshot_time);
CREATE INDEX IF NOT EXISTS idx_orderbook_run
    ON orderbook_snapshot (upload_run_id);
CREATE INDEX IF NOT EXISTS idx_orderbook_stock_daily
    ON orderbook_snapshot (stock_daily_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_technical_indicator_run_date_code
    ON technical_indicator_snapshot (upload_run_id, trade_date, stock_code)
    WHERE upload_run_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_technical_indicator_code_date
    ON technical_indicator_snapshot (stock_code, trade_date);
CREATE INDEX IF NOT EXISTS idx_technical_indicator_run
    ON technical_indicator_snapshot (upload_run_id);

CREATE OR REPLACE VIEW latest_stock_daily AS
SELECT DISTINCT ON (trade_date, stock_code) *
FROM stock_daily
ORDER BY trade_date, stock_code, created_at DESC, id DESC;

CREATE OR REPLACE VIEW latest_orderbook_snapshot AS
SELECT DISTINCT ON (snapshot_date, snapshot_time, stock_code) *
FROM orderbook_snapshot
ORDER BY snapshot_date, snapshot_time, stock_code, created_at DESC, id DESC;

ALTER TABLE upload_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE upload_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE orderbook_snapshot ENABLE ROW LEVEL SECURITY;
ALTER TABLE technical_indicator_snapshot ENABLE ROW LEVEL SECURITY;

-- No Supabase authentication mechanism is currently present in the application.
-- Keep historical tables closed to public reads/writes until an authenticated
-- application role and explicit read policy are implemented.
CREATE POLICY upload_runs_schema_stage_read ON upload_runs
    FOR SELECT USING (false);
CREATE POLICY upload_ledger_schema_stage_read ON upload_ledger
    FOR SELECT USING (false);
CREATE POLICY stock_daily_schema_stage_read ON stock_daily
    FOR SELECT USING (false);
CREATE POLICY orderbook_snapshot_schema_stage_read ON orderbook_snapshot
    FOR SELECT USING (false);
CREATE POLICY technical_indicator_schema_stage_read ON technical_indicator_snapshot
    FOR SELECT USING (false);

COMMENT ON TABLE upload_runs IS 'Historical upload/run identity for append-only Supabase persistence.';
COMMENT ON TABLE upload_ledger IS 'Upload file ledger mapped from the existing SQLite upload ledger.';
COMMENT ON TABLE stock_daily IS 'Historical daily market data mapped from SQLite, including embedded orderbook levels 1-5.';
COMMENT ON TABLE orderbook_snapshot IS 'Historical level 1-5 bid/ask orderbook snapshots.';
COMMENT ON TABLE technical_indicator_snapshot IS 'Optional persisted technical indicators matching modules/analysis.py.';
